### PR TITLE
Use package default-mysql-server

### PR DESCRIPTION
**Pull request by Quetzacoalt91**

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Weird, some tests are failing :thinking:

**Comment by PierreRambaud** [comment]
Closed and reopen for travis, PrestaShop/PrestaShop#15324 has been merged!

**Comment by Quetzacoalt91** [comment]
Unfortunately we will have to wait for the day after for `nightly`, and the release of `1.7.6.2` for the `1.7` tag to pass

**Comment by matks** [comment]
> Unfortunately we will have to wait for the day after for `nightly`, and the release of `1.7.6.2` for the `1.7` tag to pass

Is it because https://github.com/PrestaShop/PrestaShop/issues/15324 is unfixed in 1.7.6.1 ?

**Comment by Quetzacoalt91** [comment]
exactly

**Comment by matks** [comment]
It would be nice if we could build these docker images before releasing so we know we are not releasing a flawed version for docker.

But I guess this is what `nightly` tag is for 🤔

**Comment by Quetzacoalt91** [comment]
Indeed, we should have known about about that if Docker Hub notified us about the issue.

**Comment by PierreRambaud** [comment]
> It would be nice if we could build these docker images before releasing so we know we are not releasing a flawed version for docker.
> 
> But I guess this is what `nightly` tag is for

But nightly is targeting the `develop` branch and not the `1.7.6.x` :/

**Comment by matks** [comment]
> > It would be nice if we could build these docker images before releasing so we know we are not releasing a flawed version for docker.
> > But I guess this is what `nightly` tag is for
> 
> But nightly is targeting the `develop` branch and not the `1.7.6.x` :/

Caramba !

I see 2 solutions:

- add a hotfix on this repository to make 1.7.6.1 CLI-compatible, like Ready does

It's not pretty but it actually mirrors how this is done outside for shops in product: 1) fix the shop 2) submit the PR and wait for next release

- declare this issue as critical and release a 1.7.6.2 ASAP

Maybe this last one is too much but I think that "the CLI must be runnable" is a feature important enough for us to add an Integration test that runs it, wdyt ?

**Comment by Quetzacoalt91** [comment]
I'm in favor of not modifying this repository and wait for the release of 1.7.6.2. Otherwise we will add a fix we will forget to remove later.

**Comment by Quetzacoalt91** [comment]
I know that the build is failing, but as it is related to PS and not this repository, I'm merging anyway.

**Pull request merged**
